import { Roboto, Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar.js";
import ArowBack from "../components/Arow-back";
import Banner from "../components/Banner";
import Footer from "../components/Footer.js";

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
  weight: ['100', '300', '400', '500', '700', '900'],
});

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata = {
  title: "L'Entre-Deux - Village de l'Entre-Deux",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className=" h-screen w-full flex flex-col overflow-x-hidden">
      <body className=" min-h-screen min-w-full flex flex-col overflow-x-hidden bg-[#e5fafad8]/95 ">
        <ArowBack/>
        <NavBar />
        <Banner />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
