import { Roboto, Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar.js";
import ArowBack from "../components/Arow-back";
import Footer from "../components/Footer.js";

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
  weight: ['100', '300', '400', '500', '700', '900'],
});

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className=" h-full w-full overflow-hidden ">
      <body className=" min-h-full min-w-full overflow-hidden ">
        <ArowBack/>
        <NavBar />
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
